# Generated by Django 3.0.4 on 2020-03-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='status',
            new_name='type',
        ),
    ]
