# Generated by Django 3.0.3 on 2020-03-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('iso_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('iso_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=250)),
                ('continent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Country')),
            ],
        ),
    ]
