# Generated by Django 3.0.3 on 2020-03-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('C', 'Capitol'), ('R', 'Regular')], default='R', max_length=1),
        ),
    ]
